spring:
  application:
    name: bunte-app
  datasource:
    url: jdbc:postgresql://postgres:5432/myappdb
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/Bunte-App
          jwk-set-uri: http://keycloak:8080/realms/Bunte-App/protocol/openid-connect/certs

server:
  port: 8081

bunte-app:
  keycloak:
    token-uri: ${KEYCLOAK_TOKEN_URI:http://keycloak:8080/realms/Bunte-App/protocol/openid-connect/token}
    client-id: ${KEYCLOAK_CLIENT_ID:Bunte-App}
    client-secret: ${KEYCLOAK_CLIENT_SECRET:}
